### ISSUE TITLE
Followup messages after delay

### ISSUE THREAD

**Issue by cgeopapa** [ms7m/dispike#32]
What The command I want to add to my bot goes somewhat like this:

1. The bot receives the the request to do whatever it has to do (so far so good)
2. It now checks something on my remote server and chooses whether it will do action A or B
3. Once it has chosen I want it to inform the user on its choice. 
4. Do action A or B
5. Send a message that the action is done

Of course there will be a delay between steps 3 and 5, until step 4 is done. If I use followup messages it just waits until step 4 is done and then sends all messages at the same time.
Here is a sample code where I use `time.sleep` for testing:
```python
@bot.interaction.on("ping")
async def ping(ctx: IncomingDiscordInteraction) -> DiscordResponse:
    response = DiscordResponse(content="pong")
    loop = asyncio.get_event_loop()
    loop.create_task(follow(ctx))

    return response


async def follow(ctx: IncomingDiscordInteraction):
    time.sleep(2)
    followup = FollowUpMessages(bot=bot, interaction=ctx)
    responseF = DiscordResponse(follow_up_message=False)
    responseF.content = "pong follow up"
    await followup.async_create_follow_up_message(responseF)
```

I'm pretty sure I am doing something wrong.I am very unfamiliar with asyncio and event loops. Any help with that?

**Comment by ms7m** [comment]
You're on the right track. 

There is an helper method available with the ``Dispike`` object called ``.background``.  Based on your steps, you could probably have something like this.


```python

async def pong(ctx: IncomingDiscordInteraction):
    
    followup_message = FollowUpMessages(bot, interaction=ctx)
    await asyncio.sleep(2)

    response_followup = DiscordResponse(content="pong")
    await follow_up_message.async_create_follow_up_message(response_followup)


@bot.interaction.on("ping")
async def ping(ctx: IncomingDiscordInteraction) -> DiscordResponse:
    response = DiscordResponse(content="pong")


    # background 
    bot.background(pong, ctx)

    return response

```

I wouldn't use ``time`` for anything in an async function, but if you could use it if you replace ``async_create_follow_up_message`` with ``sync_create_follow_up_message``. 

I should write some documentation about this..

**Comment by cgeopapa** [comment]
`bot.background` still requires to be awaited, and if I await it I just get the same result.

**Comment by ms7m** [comment]
Ah, I see what you mean. I'll push an update to fix this behavior for ``.background``..

**Comment by ms7m** [comment]
Just pushed version 0.9.0a..

Testing with this example


```python
async def later_pong(time_recieved, interaction: IncomingDiscordInteraction):
    now_time = datetime.datetime.now()
    time_diff = (now_time - time_recieved).total_seconds() * 1000

    _followup_object = FollowUpMessages(bot, interaction=interaction)
    await asyncio.sleep(10)

    pong_message  = DiscordResponse(show_user_input=False)
    pong_message.content = f"Pong: {time_diff}ms"
    await _followup_object.async_create_follow_up_message(pong_message)


@bot.interaction.on("ping")
async def ping(ctx: IncomingDiscordInteraction) -> DiscordResponse:
    await bot.background(later_pong, datetime.datetime.now(), ctx)

    logger.info("sending response ?")
    return DiscordResponse(
        content="Ping: ..."
    )
```

Let me know if you works out for you

**Comment by cgeopapa** [comment]
There we go! Thank you!
Is there any discord server where I can join and get involved with this project? I see a lot of potential here.

**Comment by ms7m** [comment]
No problem! 

There isn't a discord server *yet*. That sounds like a good idea for the future :)
