### ISSUE TITLE
Responding to Interactions does not require a Bot Token

### ISSUE THREAD

**Issue by EthanC** [ms7m/dispike#51]
According to the [Discord Slash Commands Documentation](https://discord.com/developers/docs/interactions/slash-commands#slash-commands-interactions-and-bot-users)...

> Slash Commands and Interactions bring something entirely new to the table: the ability to interact with an application without needing a bot user in the guild. As you read through this documentation, you'll see that bot tokens are only referenced as a helpful alternative to doing a client credentials auth flow. Slash Commands do not depend on a bot user in the guild; **responding to interactions does not require a bot token**.
> 
> In many cases, you may still need a bot user. If you need to receive gateway events, or need to interact with other parts of our API (like fetching a guild, or a channel, or updating permissions on a user), those actions are all still tied to having a bot token. However, if you don't need any of those things, **you never have to add a bot user to your application** at all.

It would seem that the `bot_token` argument for initializing a Dispike object should not be required. Dropping this requirement would mean one less step to beginning a project using Dispike and would keep things as efficient as possible.

Of course, it is possible that I'm underestimating the scope in which Dispike interacts with the API. In that case, this Issue is invalid.

**Comment by ms7m** [comment]
This should be ready in the next release!

For obvious reasons, certain methods/attributes (such as ``.register``) will raise a new exception ``dispike.errors.dispike.BotTokenNotProvided``.
