### ISSUE TITLE
Support default_permission for DiscordCommand

### ISSUE THREAD

**Issue by EthanC** [ms7m/dispike#53]
- Relevant Documentation: [Slash Commands - Permissions](https://discord.com/developers/docs/interactions/slash-commands#permissions)

> You can also set a `default_permission` on your commands if you want them to be disabled by default when your app is added to a new guild. Setting `default_permission` to `false` will disallow anyone in a guild from using the command--even Administrators and guild owners--unless a specific overwrite is configured. It will also disable the command from being usable in DMs.

It would appear that this boolean value should be set on the `DiscordCommand` model after `options`.

**Comment by EthanC** [comment]
@ms7m Did you verify that adding `default_permission=False` to a `DiscordCommand` functions as expected?

Personally, a command with `default_permission=False` and no other permissions set is still usable for me (the guild owner) in my tests.

**Comment by ms7m** [comment]
Just tested it on mine. 
```python
bot.register(
    DiscordCommand(
        name="defaultpermissiontest",
        description="return simple command",
        options=[],
        default_permission=True,
    )
)
```

Flipping to ``False`` made it appear again. How does your command look?

**Comment by EthanC** [comment]
Ah, it was an error on my part, apologies. I had command permissions that I wasn't aware of which overwrote the `default_permission`. Functions as intended 👍
