### ISSUE TITLE
Possible Error in Event Callback Name Generation for Subcommands

### ISSUE THREAD

**Issue by EthanC** [ms7m/dispike#56]
My understanding is that Dispike generates callback names for commands, this process is not handled by Discord. Assuming this is in fact the case, this Issue describes what I feel to be unintuitive results from this process. When nesting a single level subcommand without the use of subcommand groups, the first argument name is included in the callback name.

The following example produces a callback name of `lorem.ipsum.dolor`.

However, the command usage is `/lorem ipsum dolor:VALUE sit:VALUE amet:VALUE`. Shouldn't the callback name be `lorem.ipsum`?

```py
DiscordCommand(
    name="lorem",
    description="...",
    options=[
        CommandOption(
            name="ipsum",
            description="...",
            type=CommandTypes.SUB_COMMAND,
            options=[
                CommandOption(
                    name="dolor",
                    description="..."
                    type=CommandTypes.STRING,
                    required=True,
                    choices=[...]
                ),
                CommandOption(
                    name="sit",
                    description="..."
                    type=CommandTypes.STRING,
                    required=True,
                    choices=[...]
                )
                CommandOption(
                    name="amet",
                    description="..."
                    type=CommandTypes.STRING,
                    required=True,
                    choices=[...]
                )
            ]
        )    
    ]
)
```

**Comment by ms7m** [comment]
Good eye, I'll drop the last value ``xxx.xxx.[xxx]``. I can see in my tests it also returns a argument value as the command callback name.
