### ISSUE TITLE
Support for Application Commands

### ISSUE THREAD

**Issue by EthanC** [ms7m/dispike#60]
> Application commands are commands that an application can register to Discord. They provide users a first-class way of interacting directly with your application that feels deeply integrated into Discord.

Relevant Documentation:

- [User Commands](https://discord.com/developers/docs/interactions/application-commands#user-commands)
- [Message Commands](https://discord.com/developers/docs/interactions/application-commands#message-commands)

![962b3b005099837db7aa811a391d2e33](https://user-images.githubusercontent.com/16727756/128939392-5310e672-6c42-4851-8b95-227bc8aae005.png)

**Comment by ms7m** [comment]
@mrshmllow go for it! -- but an FYI that the ``dev`` has seen lots of changes so you may need to catch up in #52 and #47

**Comment by mrshmllow** [comment]
schools been pretty busy but I've been keeping up some of the changes

**Comment by mrshmllow** [comment]
Will be fixed at v1b
