### ISSUE TITLE
Add users to roles using slash commands

### ISSUE THREAD

**Issue by filips123** [ms7m/dispike#62]
I would like to create a bot that creates some slash commands, for example `/roles add ROLE` and `/roles leave ROLE`, that allow users to be added/removed to/from certain roles when they use the command.

This probably isn't possible using just interactions, but if I understand [Discord docs](https://discord.com/developers/docs/interactions/receiving-and-responding#interactions-and-bot-users) correctly, it should be possible if we use a bot user/token:

> In many cases, you may still need a bot user. If you need to receive gateway events, or need to interact with other parts of our API (like fetching a guild, or a channel, or updating permissions on a user), those actions are all still tied to having a bot token.

**Comment by mrshmllow** [comment]
You will have to use the discord API. Look in the docs for how to give a user a role

**Comment by filips123** [comment]
Ok, thanks for your help.
