### ISSUE TITLE
Is 3.6+ really a caveat?

### ISSUE THREAD

**Issue by mrshmllow** [ms7m/dispike#63]
Any production environment worth it's salt should use up to date packages, especially if it's public facing. 3.6 loses security support at the end of this year, to my bad understanding isn't it just a _given_ that it doesn't support old versions?

**Comment by mrshmllow** [comment]
all of this is to say it's more of a fact rather than a caveat

**Comment by ms7m** [comment]
Many people don't upgrade until something breaks ¯\\_(ツ)_/¯. 

As long as supporting 3.6 doesn't 
- become a nightmare to maintain
- too many bandaids to keep functionality (e.g the import of ``typing_extensions``)
- lose support in upstream FastAPI or Pydantic

Let's keep it just until we can have another discussion when it loses security support later this year.
